title: Ruang Belajar - Manajemen Kualitas
description: Repositori pembelajaran mata kuliah Manajemen Kualitas
image: images/cover.jpg
domain: ruang-belajar.github.io
url: http://ruang-belajar.github.io/manajemen-kualitas
github_username:  pujangga123
lang: id-ID

remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme